config/routes.rb
Rails.application.routes.draw do
  resources :starters
  root 'pages#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/starter.rb
class Starter < ActiveRecord::Base
    
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :starters
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  devise :omniauthable, :omniauth_providers => [:facebook]
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    #user.name = auth.info.name   # assuming the user model has a name
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index 
       
       
        
    end
    
    
end

app/controllers/starters_controller.rb
class StartersController < ApplicationController
  before_action :set_starter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /starters
  # GET /starters.json
  def index
    @starters = Starter.all
  end

  # GET /starters/1
  # GET /starters/1.json
  def show
  end

  # GET /starters/new
  def new
    @starter = Starter.new
  end

  # GET /starters/1/edit
  def edit
  end

  # POST /starters
  # POST /starters.json
  def create
    @starter = current_user.starters.new(starter_params)

    respond_to do |format|
      if @starter.save
        format.html { redirect_to @starter, notice: 'Starter was successfully created.' }
        format.json { render :show, status: :created, location: @starter }
      else
        format.html { render :new }
        format.json { render json: @starter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /starters/1
  # PATCH/PUT /starters/1.json
  def update
    respond_to do |format|
      if @starter.update(starter_params)
        format.html { redirect_to @starter, notice: 'Starter was successfully updated.' }
        format.json { render :show, status: :ok, location: @starter }
      else
        format.html { render :edit }
        format.json { render json: @starter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starters/1
  # DELETE /starters/1.json
  def destroy
    @starter.destroy
    respond_to do |format|
      format.html { redirect_to starters_url, notice: 'Starter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_starter
      @starter = Starter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def starter_params
      params.require(:starter).permit(:content, :category, :upvotes, :downvotes)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/starters_helper.rb
module StartersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/index.html.erb
<%if user_signed_in?%>
Congrats <%= current_user.email%><br />
<%= link_to("Sign Out", destroy_user_session_path, :method => :delete)%><br />
<%= link_to("Edit", edit_user_registration_path)%>
<%else%>3
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '976431432508451',
      xfbml      : true,
      version    : 'v2.10'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>

nope<br />
<%= link_to("Sign In", new_user_session_path)%><br />
<%= link_to("Sign Up", new_user_registration_path)%><br />
<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
<%end%>

app/views/starters/_form.html.erb
<%= form_for(@starter) do |f| %>
  <% if @starter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@starter.errors.count, "error") %> prohibited this starter from being saved:</h2>

      <ul>
      <% @starter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :upvotes %><br>
    <%= f.text_field :upvotes %>
  </div>
  <div class="field">
    <%= f.label :downvotes %><br>
    <%= f.number_field :downvotes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/starters/edit.html.erb
<h1>Editing Starter</h1>

<%= render 'form' %>

<%= link_to 'Show', @starter %> |
<%= link_to 'Back', starters_path %>

app/views/starters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Starters</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Category</th>
      <th>Upvotes</th>
      <th>Downvotes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @starters.each do |starter| %>
      <tr>
        <td><%= starter.content %></td>
        <td><%= starter.category %></td>
        <td><%= starter.upvotes %></td>
        <td><%= starter.downvotes %></td>
        <td><%= link_to 'Show', starter %></td>
        <td><%= link_to 'Edit', edit_starter_path(starter) %></td>
        <td><%= link_to 'Destroy', starter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Starter', new_starter_path %>

app/views/starters/new.html.erb
<h1>New Starter</h1>

<%= render 'form' %>

<%= link_to 'Back', starters_path %>

app/views/starters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @starter.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @starter.category %>
</p>

<p>
  <strong>Upvotes:</strong>
  <%= @starter.upvotes %>
</p>

<p>
  <strong>Downvotes:</strong>
  <%= @starter.downvotes %>
</p>

<%= link_to 'Edit', edit_starter_path(@starter) %> |
<%= link_to 'Back', starters_path %>